version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    environment:
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
      - 'xpack.security.enabled=false'
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - c4gt_mentoring_catalog_net
    logging:
      driver: none
  mentoring-catalog-bap:
    build: './'
    container_name: c4gt-mentoring-catalog-bap
    image: c4gt/mentoring-catalog-bap:1.0
    volumes:
      - ./src/:/var/src
    ports:
      - '3009:3009'
    command: ['nodemon', 'app.js']
    networks:
      - c4gt_mentoring_catalog_net
networks:
  c4gt_mentoring_catalog_net:
    external: false